platform :ios, '12.0'
use_frameworks!

ENV['COCOAPODS_DISABLE_STATS'] = "true" ## This disabled the Sending Stats when running Pod install in terminal

target 'PopupDialog_Example' do

  pod 'PopupDialog', :path => '../'
  pod 'SwiftLint', '~> 0.35'
  
  target 'PopupDialog_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 10'
    pod 'iOSSnapshotTestCase', '~> 8.0.0'

  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
